server.port=8081
spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://${DB_HOST_AUTH}:${DB_PORT_AUTH}/${DB_NAME_AUTH}
spring.datasource.username=${DB_USERNAME_AUTH}
spring.datasource.password=${DB_PASSWORD_AUTH}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000

logging.level.com.fooddelivery.auth=DEBUG
