spring.application.name=delivery-service


server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT_DEL}/${DB_NAME_DEL}
spring.datasource.username=${DB_USERNAME_DEL}
spring.datasource.password=${DB_PASSWORD_DEL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=delivery-group
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sorokaandriy.order_service,com.sorokaandriy.delivery_service
spring.kafka.consumer.properties.spring.json.type.mapping=com.sorokaandriy.order_service.dto.OrderCreatedEvent:com.sorokaandriy.delivery_service.dto.OrderCreatedEvent,com.sorokaandriy.order_service.dto.OrderCancelledEvent:com.sorokaandriy.delivery_service.dto.OrderCancelledEvent
spring.kafka.consumer.auto-offset-reset=earliest

jwt.secret=${JWT_SECRET}


app.restaurant-service.url=http://${RESTAURANT_SERVICE_HOST}:8082/api/v1/restaurants

kafka.topics.order-created=order-created
kafka.topics.order-cancel=order-cancel
kafka.topics.delivery-accepted=delivery-accepted
kafka.topics.delivery-completed=delivery-completed

logging.level.com.sorokaandriy.delivery_service=DEBUG
