spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:postgresql://${DB_HOST_ORD}:${DB_PORT_ORD}/${DB_NAME_ORD}
spring.datasource.username=${DB_USERNAME_ORD}
spring.datasource.password=${DB_PASSWORD_ORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

jwt.secret=${JWT_SECRET}

kafka.topics.order-created=order-created
kafka.topics.order-cancel=order-cancel
app.restaurant-service.url=http://${SERVICE_HOST_RES}:8082/api/v1/restaurants

logging.level.com.sorokaandriy.order_service=DEBUG