server.port=8088
spring.application.name=api-gateway

# Redis (rate limiting)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000ms

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.server.webflux.routes[0].metadata.response-timeout=5000

spring.cloud.gateway.server.webflux.routes[1].id=restaurant-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/restaurants/**

spring.cloud.gateway.server.webflux.routes[2].id=category-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/categories/**

spring.cloud.gateway.server.webflux.routes[3].id=order-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.server.webflux.routes[4].id=delivery-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/deliveries/**

spring.cloud.gateway.server.webflux.routes[5].id=rider-tracking
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/tracking/**

spring.cloud.gateway.server.webflux.routes[6].id=payment-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.server.webflux.routes[7].id=notification-service
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/notifications/**

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*

management.endpoints.web.exposure.include=health,gatewayserverwebflux

logging.level.com.sorokaandriy.api_gateway=DEBUG
