spring.application.name=restaurant-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT_RES}/${DB_NAME_RES}
spring.datasource.username=${DB_USERNAME_RES}
spring.datasource.password=${DB_PASSWORD_RES}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000ms


spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

logging.level.com.sorokaandriy.restaurant_service=DEBUG


